import os
from setuptools import setup
import subprocess

# REDONE 20171023 TO CONFORM GREGORY setup.py
#   #packages=[]   #  directory with __init__.py
#   #modules=[]    #  single files in root dir
# search for       PyPackMan.ipynb

def read(fname):
    return open(os.path.join(os.path.dirname(__file__), fname)).read()

def package_files(directory):
    paths = []
    for (path, directories, filenames) in os.walk(directory):
        for filename in filenames:
            paths.append(os.path.join('..', path, filename))
    return paths
extra_files = package_files('NuPhyPy/') # here i dont know 20171022

#############################   version trick with git:  must.install
version_py = os.path.join(os.path.dirname(__file__), 'version.py')
try:
    version_git = subprocess.check_output(["git", "describe"]).decode("utf8").rstrip()
    print("D... version=", version_git)
except:
    with open(version_py, 'r') as fh:
        version_git = open(version_py).read().strip().split('=')[-1].replace('"','')
version_msg="# Do not edit this file, pipeline versioning is governed by git tags"
with open(version_py, 'w') as fh:
    fh.write(version_msg + str(os.linesep) + "__version__=" + version_git)


################################
#
# MAIN PART
#
#################################
    
setup(
    name = "NuPhyPy",
     version="{ver}".format(ver=version_git),  # this comes from http://blogs.nopcode.org/brainstorm/2013/05/20/pragmatic-python-versioning-via-setuptools-and-git-tags/
    zip_safe= False,
    author = "jaromir mrazek",
    author_email = "jaromrax@gmail.com",
    description = ("A Nuclear Physics Python package "
                                   "to address many things: kinematics, srim, fresco,....."),
    license = "GPLv2",
    keywords = "nuclear physics",
    url = "http://www.spiral2.cz",
    py_modules=['NuPhyPy'],
    packages=['NuPhyPy'],
    package_data={'':extra_files},
    scripts=['bin/nuphy.py'],
    long_description=read('README.md'),
    classifiers=[
        "Development Status :: 2 - Pre-Alpha",
        "Topic :: Utilities",
        "License :: OSI Approved :: GNU General Public License v2 (GPLv2)",
    ],
)
